on: [push, pull_request]
name: Sanity
jobs:
  build:
    name: "Run go sanity tools"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: Build
      run: make
    - name: Install golint
      run: go get -u golang.org/x/lint/golint
    - name: Lint
      run: make lint
    - name: Fmt
      run: make fmt
    - name: Vet
      run: make vet
